// eslint-disable-next-line import/prefer-default-export
export const PROJECTS = [
  {
    id: 0,
    image: 'images/projects/blocks.png',
    name: 'Blocks',
    description: 'Get the colored blocks out of the square by getting the grey blocks out of the way.',
    techs: ['images/techs/objc.png', 'images/techs/ios.png'],
    links: ['https://github.com/alainfurter/ios-blocks-game', '', ''],
  },
  {
    id: 1,
    image: 'images/projects/lights.png',
    name: 'Lights',
    description: 'An addictive game for iOS devices where you refracture laser lights to reach their targets.',
    techs: ['images/techs/objc.png', 'images/techs/ios.png'],
    links: ['https://github.com/alainfurter/ios-laser-game', '', ''],
  },
  {
    id: 2,
    image: 'images/projects/devpage.png',
    name: 'Developer Portfolio',
    description: 'A very basic developer portfolio page in HTML, CSS, JS',
    techs: ['images/techs/html.png', 'images/techs/css.png', 'images/techs/js.png', 'images/techs/vite.png'],
    links: ['https://github.com/alainfurter/rtc-viteproject3', 'https://profound-peony-7100d9.netlify.app', ''],
  },
  {
    id: 3,
    image: 'images/projects/bestbuy.png',
    name: 'Visualization: Best Buy Store',
    description: 'Visualization of the Best Buy Landing page in HTML, CSS and JS.',
    techs: ['images/techs/html.png', 'images/techs/css.png', 'images/techs/js.png'],
    links: ['https://github.com/alainfurter/rtc-jsproject2', 'https://chic-babka-de1d5d.netlify.app', ''],
  },
  {
    id: 4,
    image: 'images/projects/fielmann.png',
    name: 'Visualization: Fielmann Store',
    description: 'Visualization of the Fielmann Landing page in HTML, CSS and JS.',
    techs: ['images/techs/html.png', 'images/techs/css.png', 'images/techs/js.png'],
    links: ['https://github.com/alainfurter/rtc-cssproject', 'https://curious-froyo-db19c1.netlify.app', ''],
  },
  {
    id: 4,
    image: 'images/projects/swisstransit.png',
    name: 'Swiss Transit',
    description: 'First ever public transport app for iPad in Switzerland in 2013.',
    techs: ['images/techs/objc.png', 'images/techs/ios.png', 'images/techs/sql.png'],
    links: ['https://github.com/alainfurter/ios-swiss-transit', 'https://www.zonezeroapps.com/swisstransit/index.html', ''],
  },
  {
    id: 5,
    image: 'images/projects/swissplates.png',
    name: 'Swiss Plates',
    description: 'Search and locate car owners in Switzerland by their number plates.',
    techs: ['images/techs/objc.png', 'images/techs/ios.png'],
    links: ['https://github.com/alainfurter/ios-swiss-transit', 'https://www.zonezeroapps.com/swissplates/index.html', 'https://apps.apple.com/at/app/swiss-plates-pro/id431075139'],
  },
  {
    id: 6,
    image: 'images/projects/chainrays.png',
    name: 'Chain Rays',
    description: 'Blockchain analytics plattform - Under development',
    techs: ['images/techs/react.png', 'images/techs/nodejs.png', 'images/techs/mongodb.png', 'images/techs/sql.png'],
    links: ['https://github.com/chainrays', 'https://www.chainrays.com', ''],
  },
  {
    id: 7,
    image: 'images/projects/peaksviewer.png',
    name: 'Peaks Viewer',
    description: '3D contour shaded model visualizations of DEM satellite data of the mountains and their peaks.',
    techs: ['images/techs/c++.png', 'images/techs/metal.png', 'images/techs/objc.png', 'images/techs/ios.png'],
    links: ['', 'https://www.peaksviewer.com', ''],
  },
  {
    id: 8,
    image: 'images/projects/woprcrt.png',
    name: 'WOPR CRT',
    description: 'WOPR (Joshua) War Games movie like game hub, computer and Chat GPT terminal.',
    techs: ['images/techs/react.png', 'images/techs/nodejs.png', 'images/techs/vite.png', 'images/techs/js.png'],
    links: ['https://github.com/alainfurter/woprcrt-terminal', 'https://woprcrt.com', ''],
  },
];
